version: '2.3'

services:
  cil-net:
    build:
      context: ./../../
      dockerfile: ./imitation-learning-pytorch/docker/Dockerfile
      shm_size: '40gb'
    image: cil-net-image:1.0
    runtime: nvidia
    shm_size: '40gb'
    volumes:
      - ./data-and-checkpoints:/workspace/data-and-checkpoints
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  data-and-checkpoints:
